### ISSUE TITLE
Sensors constantly going offline

### ISSUE THREAD

**Issue by ramielrowe** [Matvei27/sonoff#1]
Really appreciate this script and it seems to be providing all the sensor details. My only issue is that the sensors seem to get flagged as offline quite often. Are you experiencing that as well?

I also noticed almost all messages transmitted to the device are failing. Example:

```
  Messages Transmitted to Device: 87
  Messages Transmitted to Device (Failures): 85
```

Lemme know if I can provide any other details.

**Comment by Matvei27** [comment]
It sounds to me like the device is too far from the hub. Can you check in the IDE, is this going through any repeaters?

The device is designed to be marked offline if there is no response after 2 hours and 1 minute.

**Comment by ramielrowe** [comment]
One is through a repeater, others are direct and even one is in the same room as the hub.

Just checked all of my sensors and their checkInterval was set at 720s, which I think case from a previous device handler before I switched to yours. Updated all of the devices, and now things look correct. Hopefully that was it. Thanks for the tip!
